// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type NavegacionDocumentDataSlicesSlice =
  | NavegacionSliceSlice
  | PrismicCmsSliceSlice
  | SitesSliceSlice
  | SliderSliceSlice
  | SeoSliceSlice
  | PreciosSliceSlice
  | MarcasSliceSlice
  | HeroSectionSlice
  | CtaSliceSlice;

/**
 * Content for Plomoo documents
 */
interface NavegacionDocumentData {
  /**
   * Slice Zone field in *Plomoo*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navegacion.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NavegacionDocumentDataSlicesSlice> /**
   * Meta Tittle field in *Plomoo*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navegacion.meta_tittle
   * - **Tab**: SEOMain
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  meta_tittle: prismic.RichTextField;

  /**
   * Meta Description field in *Plomoo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navegacion.meta_description
   * - **Tab**: SEOMain
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Thumbnail field in *Plomoo*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navegacion.meta_thumbnail
   * - **Tab**: SEOMain
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_thumbnail: prismic.ImageField<never>;
}

/**
 * Plomoo document from Prismic
 *
 * - **API ID**: `navegacion`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavegacionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<NavegacionDocumentData>,
    "navegacion",
    Lang
  >;

export type AllDocumentTypes = NavegacionDocument;

/**
 * Primary content in *CtaSlice → Default → Primary*
 */
export interface CtaSliceSliceDefaultPrimary {
  /**
   * Titulo field in *CtaSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_slice.default.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Subtitulo field in *CtaSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_slice.default.primary.subtitulo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitulo: prismic.KeyTextField;

  /**
   * BotonLink field in *CtaSlice → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_slice.default.primary.botonlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  botonlink: prismic.LinkField;

  /**
   * BotonLabel field in *CtaSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_slice.default.primary.botonlabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  botonlabel: prismic.KeyTextField;

  /**
   * ImagenCTA field in *CtaSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_slice.default.primary.imagencta
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagencta: prismic.ImageField<never>;
}

/**
 * Default variation for CtaSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CtaSlice*
 */
type CtaSliceSliceVariation = CtaSliceSliceDefault;

/**
 * CtaSlice Shared Slice
 *
 * - **API ID**: `cta_slice`
 * - **Description**: CtaSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSliceSlice = prismic.SharedSlice<
  "cta_slice",
  CtaSliceSliceVariation
>;

/**
 * Item in *HeroSection → Default → Primary → GroupHeroSection*
 */
export interface HeroSectionSliceDefaultPrimaryGroupherosectionItem {
  /**
   * label field in *HeroSection → Default → Primary → GroupHeroSection*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.groupherosection[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * icono field in *HeroSection → Default → Primary → GroupHeroSection*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.groupherosection[].icono
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icono: prismic.ImageField<never>;
}

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * Titulo field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Subtitulo field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.subtitulo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitulo: prismic.KeyTextField;

  /**
   * GroupHeroSection field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.groupherosection[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  groupherosection: prismic.GroupField<
    Simplify<HeroSectionSliceDefaultPrimaryGroupherosectionItem>
  >;

  /**
   * BotonLink field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.botonlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  botonlink: prismic.LinkField;

  /**
   * BotonTexto field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.botontexto
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  botontexto: prismic.KeyTextField;

  /**
   * LabelLink field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.labellink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  labellink: prismic.LinkField;

  /**
   * Label field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * ImagenFondo field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.imagenfondo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagenfondo: prismic.ImageField<never>;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Item in *MarcasSlice → Default → Primary → Grouplogos*
 */
export interface MarcasSliceSliceDefaultPrimaryGrouplogosItem {
  /**
   * Imagenlogo field in *MarcasSlice → Default → Primary → Grouplogos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: marcas_slice.default.primary.grouplogos[].imagenlogo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagenlogo: prismic.ImageField<never>;
}

/**
 * Primary content in *MarcasSlice → Default → Primary*
 */
export interface MarcasSliceSliceDefaultPrimary {
  /**
   * LabelDescripcion field in *MarcasSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: marcas_slice.default.primary.labeldescripcion
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  labeldescripcion: prismic.RichTextField;

  /**
   * Grouplogos field in *MarcasSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: marcas_slice.default.primary.grouplogos[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  grouplogos: prismic.GroupField<
    Simplify<MarcasSliceSliceDefaultPrimaryGrouplogosItem>
  >;
}

/**
 * Default variation for MarcasSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MarcasSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MarcasSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MarcasSlice*
 */
type MarcasSliceSliceVariation = MarcasSliceSliceDefault;

/**
 * MarcasSlice Shared Slice
 *
 * - **API ID**: `marcas_slice`
 * - **Description**: MarcasSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MarcasSliceSlice = prismic.SharedSlice<
  "marcas_slice",
  MarcasSliceSliceVariation
>;

/**
 * Item in *NavegacionSlice → Default → Primary → NavegacionMenu*
 */
export interface NavegacionSliceSliceDefaultPrimaryNavegacionmenuItem {
  /**
   * SectionLabel field in *NavegacionSlice → Default → Primary → NavegacionMenu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navegacion_slice.default.primary.navegacionmenu[].sectionlabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sectionlabel: prismic.KeyTextField;

  /**
   * SectionLink field in *NavegacionSlice → Default → Primary → NavegacionMenu*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: navegacion_slice.default.primary.navegacionmenu[].sectionlink
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  sectionlink: prismic.SelectField<"1" | "2">;

  /**
   * Boton field in *NavegacionSlice → Default → Primary → NavegacionMenu*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: navegacion_slice.default.primary.navegacionmenu[].boton
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  boton: prismic.BooleanField;

  /**
   * BotonLink field in *NavegacionSlice → Default → Primary → NavegacionMenu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navegacion_slice.default.primary.navegacionmenu[].botonlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  botonlink: prismic.LinkField;
}

/**
 * Primary content in *NavegacionSlice → Default → Primary*
 */
export interface NavegacionSliceSliceDefaultPrimary {
  /**
   * Logo field in *NavegacionSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navegacion_slice.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * NavegacionMenu field in *NavegacionSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navegacion_slice.default.primary.navegacionmenu[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navegacionmenu: prismic.GroupField<
    Simplify<NavegacionSliceSliceDefaultPrimaryNavegacionmenuItem>
  >;

  /**
   * BotonLink field in *NavegacionSlice → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navegacion_slice.default.primary.botonlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  botonlink: prismic.LinkField;

  /**
   * BotonTexto field in *NavegacionSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navegacion_slice.default.primary.botontexto
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  botontexto: prismic.KeyTextField;
}

/**
 * Default variation for NavegacionSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavegacionSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavegacionSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NavegacionSlice*
 */
type NavegacionSliceSliceVariation = NavegacionSliceSliceDefault;

/**
 * NavegacionSlice Shared Slice
 *
 * - **API ID**: `navegacion_slice`
 * - **Description**: NavegacionSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavegacionSliceSlice = prismic.SharedSlice<
  "navegacion_slice",
  NavegacionSliceSliceVariation
>;

/**
 * Item in *PreciosSlice → Default → Primary → GroupPrecios*
 */
export interface PreciosSliceSliceDefaultPrimaryGrouppreciosItem {
  /**
   * Subtitulo field in *PreciosSlice → Default → Primary → GroupPrecios*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: precios_slice.default.primary.groupprecios[].subtitulo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitulo: prismic.KeyTextField;

  /**
   * Descripcion field in *PreciosSlice → Default → Primary → GroupPrecios*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: precios_slice.default.primary.groupprecios[].descripcion
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descripcion: prismic.KeyTextField;
}

/**
 * Primary content in *PreciosSlice → Default → Primary*
 */
export interface PreciosSliceSliceDefaultPrimary {
  /**
   * Titulo field in *PreciosSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: precios_slice.default.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * GroupPrecios field in *PreciosSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: precios_slice.default.primary.groupprecios[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  groupprecios: prismic.GroupField<
    Simplify<PreciosSliceSliceDefaultPrimaryGrouppreciosItem>
  >;
}

/**
 * Default variation for PreciosSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PreciosSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PreciosSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PreciosSlice*
 */
type PreciosSliceSliceVariation = PreciosSliceSliceDefault;

/**
 * PreciosSlice Shared Slice
 *
 * - **API ID**: `precios_slice`
 * - **Description**: PreciosSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PreciosSliceSlice = prismic.SharedSlice<
  "precios_slice",
  PreciosSliceSliceVariation
>;

/**
 * Item in *PrismicCmsSlice → Default → Primary → GroupDescripcion*
 */
export interface PrismicCmsSliceSliceDefaultPrimaryGroupdescripcionItem {
  /**
   * descripcion field in *PrismicCmsSlice → Default → Primary → GroupDescripcion*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: prismic_cms_slice.default.primary.groupdescripcion[].descripcion
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descripcion: prismic.KeyTextField;

  /**
   * Icono field in *PrismicCmsSlice → Default → Primary → GroupDescripcion*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: prismic_cms_slice.default.primary.groupdescripcion[].icono
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icono: prismic.ImageField<never>;
}

/**
 * Primary content in *PrismicCmsSlice → Default → Primary*
 */
export interface PrismicCmsSliceSliceDefaultPrimary {
  /**
   * Titulo field in *PrismicCmsSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: prismic_cms_slice.default.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Subtitulo field in *PrismicCmsSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: prismic_cms_slice.default.primary.subtitulo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitulo: prismic.KeyTextField;

  /**
   * LinkLabel field in *PrismicCmsSlice → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: prismic_cms_slice.default.primary.linklabel
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linklabel: prismic.LinkField;

  /**
   * Label field in *PrismicCmsSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: prismic_cms_slice.default.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * GroupDescripcion field in *PrismicCmsSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: prismic_cms_slice.default.primary.groupdescripcion[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  groupdescripcion: prismic.GroupField<
    Simplify<PrismicCmsSliceSliceDefaultPrimaryGroupdescripcionItem>
  >;

  /**
   * Imagen Muestra field in *PrismicCmsSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: prismic_cms_slice.default.primary.imagen_muestra
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagen_muestra: prismic.ImageField<never>;
}

/**
 * Default variation for PrismicCmsSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PrismicCmsSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PrismicCmsSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PrismicCmsSlice*
 */
type PrismicCmsSliceSliceVariation = PrismicCmsSliceSliceDefault;

/**
 * PrismicCmsSlice Shared Slice
 *
 * - **API ID**: `prismic_cms_slice`
 * - **Description**: PrismicCmsSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PrismicCmsSliceSlice = prismic.SharedSlice<
  "prismic_cms_slice",
  PrismicCmsSliceSliceVariation
>;

/**
 * Item in *SeoSlice → Default → Primary → GroupRedesSociales*
 */
export interface SeoSliceSliceDefaultPrimaryGroupredessocialesItem {
  /**
   * LinkIcon field in *SeoSlice → Default → Primary → GroupRedesSociales*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.groupredessociales[].linkicon
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkicon: prismic.LinkField;

  /**
   * icono field in *SeoSlice → Default → Primary → GroupRedesSociales*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.groupredessociales[].icono
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icono: prismic.ImageField<never>;
}

/**
 * Item in *SeoSlice → Default → Primary → GroupLabelOne*
 */
export interface SeoSliceSliceDefaultPrimaryGrouplabeloneItem {
  /**
   * LinkLabel field in *SeoSlice → Default → Primary → GroupLabelOne*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.grouplabelone[].linklabel
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linklabel: prismic.LinkField;

  /**
   * Label field in *SeoSlice → Default → Primary → GroupLabelOne*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.grouplabelone[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *SeoSlice → Default → Primary → GroupLabelTwo*
 */
export interface SeoSliceSliceDefaultPrimaryGrouplabeltwoItem {
  /**
   * LinkLabel field in *SeoSlice → Default → Primary → GroupLabelTwo*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.grouplabeltwo[].linklabel
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linklabel: prismic.LinkField;

  /**
   * Label field in *SeoSlice → Default → Primary → GroupLabelTwo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.grouplabeltwo[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *SeoSlice → Default → Primary → GroupLabelThree*
 */
export interface SeoSliceSliceDefaultPrimaryGrouplabelthreeItem {
  /**
   * LinkLabel field in *SeoSlice → Default → Primary → GroupLabelThree*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.grouplabelthree[].linklabel
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linklabel: prismic.LinkField;

  /**
   * Label field in *SeoSlice → Default → Primary → GroupLabelThree*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.grouplabelthree[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *SeoSlice → Default → Primary → GroupLabelFour*
 */
export interface SeoSliceSliceDefaultPrimaryGrouplabelfourItem {
  /**
   * LinkLabel field in *SeoSlice → Default → Primary → GroupLabelFour*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.grouplabelfour[].linklabel
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linklabel: prismic.LinkField;

  /**
   * Label field in *SeoSlice → Default → Primary → GroupLabelFour*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.grouplabelfour[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *SeoSlice → Default → Primary → GroupLabelFive*
 */
export interface SeoSliceSliceDefaultPrimaryGrouplabelfiveItem {
  /**
   * LinkLabel field in *SeoSlice → Default → Primary → GroupLabelFive*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.grouplabelfive[].linklabel
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linklabel: prismic.LinkField;

  /**
   * Label field in *SeoSlice → Default → Primary → GroupLabelFive*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.grouplabelfive[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *SeoSlice → Default → Primary → GroupLabelSix*
 */
export interface SeoSliceSliceDefaultPrimaryGrouplabelsixItem {
  /**
   * LinkLabel field in *SeoSlice → Default → Primary → GroupLabelSix*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.grouplabelsix[].linklabel
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linklabel: prismic.LinkField;

  /**
   * Label field in *SeoSlice → Default → Primary → GroupLabelSix*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.grouplabelsix[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *SeoSlice → Default → Primary → GroupLabelSeven*
 */
export interface SeoSliceSliceDefaultPrimaryGrouplabelsevenItem {
  /**
   * LinkLabel field in *SeoSlice → Default → Primary → GroupLabelSeven*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.grouplabelseven[].linklabel
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linklabel: prismic.LinkField;

  /**
   * Label field in *SeoSlice → Default → Primary → GroupLabelSeven*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.grouplabelseven[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *SeoSlice → Default → Primary → GroupLabelEight*
 */
export interface SeoSliceSliceDefaultPrimaryGrouplabeleightItem {
  /**
   * LinkLabel field in *SeoSlice → Default → Primary → GroupLabelEight*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.grouplabeleight[].linklabel
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linklabel: prismic.LinkField;

  /**
   * Label field in *SeoSlice → Default → Primary → GroupLabelEight*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.grouplabeleight[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Primary content in *SeoSlice → Default → Primary*
 */
export interface SeoSliceSliceDefaultPrimary {
  /**
   * Logo field in *SeoSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * LabelRights field in *SeoSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.labelrights
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  labelrights: prismic.KeyTextField;

  /**
   * GroupRedesSociales field in *SeoSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.groupredessociales[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  groupredessociales: prismic.GroupField<
    Simplify<SeoSliceSliceDefaultPrimaryGroupredessocialesItem>
  >;

  /**
   * LabelOne field in *SeoSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.labelone
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  labelone: prismic.KeyTextField;

  /**
   * GroupLabelOne field in *SeoSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.grouplabelone[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  grouplabelone: prismic.GroupField<
    Simplify<SeoSliceSliceDefaultPrimaryGrouplabeloneItem>
  >;

  /**
   * LabelTwo field in *SeoSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.labeltwo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  labeltwo: prismic.KeyTextField;

  /**
   * GroupLabelTwo field in *SeoSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.grouplabeltwo[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  grouplabeltwo: prismic.GroupField<
    Simplify<SeoSliceSliceDefaultPrimaryGrouplabeltwoItem>
  >;

  /**
   * LabelThree field in *SeoSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.labelthree
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  labelthree: prismic.KeyTextField;

  /**
   * GroupLabelThree field in *SeoSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.grouplabelthree[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  grouplabelthree: prismic.GroupField<
    Simplify<SeoSliceSliceDefaultPrimaryGrouplabelthreeItem>
  >;

  /**
   * LabelFour field in *SeoSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.labelfour
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  labelfour: prismic.KeyTextField;

  /**
   * GroupLabelFour field in *SeoSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.grouplabelfour[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  grouplabelfour: prismic.GroupField<
    Simplify<SeoSliceSliceDefaultPrimaryGrouplabelfourItem>
  >;

  /**
   * LabelFive field in *SeoSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.labelfive
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  labelfive: prismic.KeyTextField;

  /**
   * GroupLabelFive field in *SeoSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.grouplabelfive[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  grouplabelfive: prismic.GroupField<
    Simplify<SeoSliceSliceDefaultPrimaryGrouplabelfiveItem>
  >;

  /**
   * LabelSix field in *SeoSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.labelsix
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  labelsix: prismic.KeyTextField;

  /**
   * GroupLabelSix field in *SeoSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.grouplabelsix[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  grouplabelsix: prismic.GroupField<
    Simplify<SeoSliceSliceDefaultPrimaryGrouplabelsixItem>
  >;

  /**
   * LabelSeven field in *SeoSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.labelseven
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  labelseven: prismic.KeyTextField;

  /**
   * GroupLabelSeven field in *SeoSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.grouplabelseven[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  grouplabelseven: prismic.GroupField<
    Simplify<SeoSliceSliceDefaultPrimaryGrouplabelsevenItem>
  >;

  /**
   * LabelEight field in *SeoSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.labeleight
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  labeleight: prismic.KeyTextField;

  /**
   * GroupLabelEight field in *SeoSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: seo_slice.default.primary.grouplabeleight[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  grouplabeleight: prismic.GroupField<
    Simplify<SeoSliceSliceDefaultPrimaryGrouplabeleightItem>
  >;
}

/**
 * Default variation for SeoSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SeoSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SeoSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SeoSlice*
 */
type SeoSliceSliceVariation = SeoSliceSliceDefault;

/**
 * SeoSlice Shared Slice
 *
 * - **API ID**: `seo_slice`
 * - **Description**: SeoSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SeoSliceSlice = prismic.SharedSlice<
  "seo_slice",
  SeoSliceSliceVariation
>;

/**
 * Item in *SitesSlice → Default → Primary → GroupSites*
 */
export interface SitesSliceSliceDefaultPrimaryGroupsitesItem {
  /**
   * Subtítulo field in *SitesSlice → Default → Primary → GroupSites*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sites_slice.default.primary.groupsites[].subtitulo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitulo: prismic.KeyTextField;

  /**
   * Descripcion field in *SitesSlice → Default → Primary → GroupSites*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sites_slice.default.primary.groupsites[].descripcion
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descripcion: prismic.KeyTextField;

  /**
   * Imagen Sites field in *SitesSlice → Default → Primary → GroupSites*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sites_slice.default.primary.groupsites[].imagen_sites
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagen_sites: prismic.ImageField<never>;
}

/**
 * Primary content in *SitesSlice → Default → Primary*
 */
export interface SitesSliceSliceDefaultPrimary {
  /**
   * Titulo field in *SitesSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sites_slice.default.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * GroupSites field in *SitesSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: sites_slice.default.primary.groupsites[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  groupsites: prismic.GroupField<
    Simplify<SitesSliceSliceDefaultPrimaryGroupsitesItem>
  >;
}

/**
 * Default variation for SitesSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SitesSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SitesSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SitesSlice*
 */
type SitesSliceSliceVariation = SitesSliceSliceDefault;

/**
 * SitesSlice Shared Slice
 *
 * - **API ID**: `sites_slice`
 * - **Description**: SitesSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SitesSliceSlice = prismic.SharedSlice<
  "sites_slice",
  SitesSliceSliceVariation
>;

/**
 * Item in *SliderSlice → Default → Primary → GroupImages*
 */
export interface SliderSliceSliceDefaultPrimaryGroupimagesItem {
  /**
   * imagen field in *SliderSlice → Default → Primary → GroupImages*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slider_slice.default.primary.groupimages[].imagen
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagen: prismic.ImageField<never>;
}

/**
 * Primary content in *SliderSlice → Default → Primary*
 */
export interface SliderSliceSliceDefaultPrimary {
  /**
   * GroupImages field in *SliderSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: slider_slice.default.primary.groupimages[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  groupimages: prismic.GroupField<
    Simplify<SliderSliceSliceDefaultPrimaryGroupimagesItem>
  >;
}

/**
 * Default variation for SliderSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SliderSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SliderSlice*
 */
type SliderSliceSliceVariation = SliderSliceSliceDefault;

/**
 * SliderSlice Shared Slice
 *
 * - **API ID**: `slider_slice`
 * - **Description**: SliderSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderSliceSlice = prismic.SharedSlice<
  "slider_slice",
  SliderSliceSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      NavegacionDocument,
      NavegacionDocumentData,
      NavegacionDocumentDataSlicesSlice,
      AllDocumentTypes,
      CtaSliceSlice,
      CtaSliceSliceDefaultPrimary,
      CtaSliceSliceVariation,
      CtaSliceSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimaryGroupherosectionItem,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      MarcasSliceSlice,
      MarcasSliceSliceDefaultPrimaryGrouplogosItem,
      MarcasSliceSliceDefaultPrimary,
      MarcasSliceSliceVariation,
      MarcasSliceSliceDefault,
      NavegacionSliceSlice,
      NavegacionSliceSliceDefaultPrimaryNavegacionmenuItem,
      NavegacionSliceSliceDefaultPrimary,
      NavegacionSliceSliceVariation,
      NavegacionSliceSliceDefault,
      PreciosSliceSlice,
      PreciosSliceSliceDefaultPrimaryGrouppreciosItem,
      PreciosSliceSliceDefaultPrimary,
      PreciosSliceSliceVariation,
      PreciosSliceSliceDefault,
      PrismicCmsSliceSlice,
      PrismicCmsSliceSliceDefaultPrimaryGroupdescripcionItem,
      PrismicCmsSliceSliceDefaultPrimary,
      PrismicCmsSliceSliceVariation,
      PrismicCmsSliceSliceDefault,
      SeoSliceSlice,
      SeoSliceSliceDefaultPrimaryGroupredessocialesItem,
      SeoSliceSliceDefaultPrimaryGrouplabeloneItem,
      SeoSliceSliceDefaultPrimaryGrouplabeltwoItem,
      SeoSliceSliceDefaultPrimaryGrouplabelthreeItem,
      SeoSliceSliceDefaultPrimaryGrouplabelfourItem,
      SeoSliceSliceDefaultPrimaryGrouplabelfiveItem,
      SeoSliceSliceDefaultPrimaryGrouplabelsixItem,
      SeoSliceSliceDefaultPrimaryGrouplabelsevenItem,
      SeoSliceSliceDefaultPrimaryGrouplabeleightItem,
      SeoSliceSliceDefaultPrimary,
      SeoSliceSliceVariation,
      SeoSliceSliceDefault,
      SitesSliceSlice,
      SitesSliceSliceDefaultPrimaryGroupsitesItem,
      SitesSliceSliceDefaultPrimary,
      SitesSliceSliceVariation,
      SitesSliceSliceDefault,
      SliderSliceSlice,
      SliderSliceSliceDefaultPrimaryGroupimagesItem,
      SliderSliceSliceDefaultPrimary,
      SliderSliceSliceVariation,
      SliderSliceSliceDefault,
    };
  }
}
