// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  agenda: defineAsyncComponent(() => import("./Agenda/index.vue")),
  cta_slice: defineAsyncComponent(() => import("./CtaSlice/index.vue")),
  hero_section: defineAsyncComponent(() => import("./HeroSection/index.vue")),
  marcas_slice: defineAsyncComponent(() => import("./MarcasSlice/index.vue")),
  navegacion_slice: defineAsyncComponent(
    () => import("./NavegacionSlice/index.vue"),
  ),
  precios_slice: defineAsyncComponent(() => import("./PreciosSlice/index.vue")),
  prismic_cms_slice: defineAsyncComponent(
    () => import("./PrismicCmsSlice/index.vue"),
  ),
  seo_slice: defineAsyncComponent(() => import("./SeoSlice/index.vue")),
  sites_slice: defineAsyncComponent(() => import("./SitesSlice/index.vue")),
  slider_slice: defineAsyncComponent(() => import("./SliderSlice/index.vue")),
});
